services:
  # PHP (Laravel) xizmat
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educrm_php
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - mysql

  # MySQL xizmati
  mysql:
    image: mysql:5.7
    container_name: educrm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}   
      MYSQL_DATABASE: ${DB_DATABASE}        
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    expose:
      - 3306

  # Nginx xizmat
  web:
    container_name: educrm_web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}
